### PR TITLE
Updated

### PR DESCRIPTION
**Pull request by 0p3r4t0r**
Dear Desmos,

I discovered this old app while riffling through your GitHub. Valentines day being right around the corner I decided to update it so that I could use it in my class. The merge adds an additional graph to the app and updates the JS dependencies. The most significant changes are the updated version of express, and the porting from jade to pug templates.

I work in Tokyo and teach in both English and Japanese and have also made another version of that app that offers support for Japanese and English. I could create a pull request for that if you would like.

Hope you have a happy Valentines Day!

### CODE REVIEW

**Comment by eluberoff** [comment]
This is so great -- thank you! I'm going to cherry pick some of these commits right now.

**Comment by eluberoff** [comment]
manually cherry-picked:
* 523bd83 &  fcdefd4

cherry-picked:
* 09dec87
* 72b2772

May I add a quick thank you to the attribution page?

**Comment by eluberoff** [comment]
Btw -- the site is now live at http://www.mathogram.com/

**Comment by 0p3r4t0r** [comment]
Absolutely, glad I was able to help the project along. I've had a blast using this at work. Much thanks to yourself and the team at Desmos for making this app. Happy Valentines day!

**Pull request closed without merging**
